// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package sample_package_0407

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// Zhaoh0407AaaClient is the client API for Zhaoh0407Aaa service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Zhaoh0407AaaClient interface {
	SayHello123(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type zhaoh0407AaaClient struct {
	cc grpc.ClientConnInterface
}

func NewZhaoh0407AaaClient(cc grpc.ClientConnInterface) Zhaoh0407AaaClient {
	return &zhaoh0407AaaClient{cc}
}

func (c *zhaoh0407AaaClient) SayHello123(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/sample_module_0407.sample_package_0407.Zhaoh0407aaa/SayHello123", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Zhaoh0407AaaServer is the server API for Zhaoh0407Aaa service.
// All implementations must embed UnimplementedZhaoh0407AaaServer
// for forward compatibility
type Zhaoh0407AaaServer interface {
	SayHello123(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedZhaoh0407AaaServer()
}

// UnimplementedZhaoh0407AaaServer must be embedded to have forward compatible implementations.
type UnimplementedZhaoh0407AaaServer struct {
}

func (UnimplementedZhaoh0407AaaServer) SayHello123(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello123 not implemented")
}
func (UnimplementedZhaoh0407AaaServer) mustEmbedUnimplementedZhaoh0407AaaServer() {}

// UnsafeZhaoh0407AaaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Zhaoh0407AaaServer will
// result in compilation errors.
type UnsafeZhaoh0407AaaServer interface {
	mustEmbedUnimplementedZhaoh0407AaaServer()
}

func RegisterZhaoh0407AaaServer(s grpc.ServiceRegistrar, srv Zhaoh0407AaaServer) {
	s.RegisterService(&Zhaoh0407Aaa_ServiceDesc, srv)
}

func _Zhaoh0407Aaa_SayHello123_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Zhaoh0407AaaServer).SayHello123(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sample_module_0407.sample_package_0407.Zhaoh0407aaa/SayHello123",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Zhaoh0407AaaServer).SayHello123(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Zhaoh0407Aaa_ServiceDesc is the grpc.ServiceDesc for Zhaoh0407Aaa service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Zhaoh0407Aaa_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sample_module_0407.sample_package_0407.Zhaoh0407aaa",
	HandlerType: (*Zhaoh0407AaaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello123",
			Handler:    _Zhaoh0407Aaa_SayHello123_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Zhaoh0407.proto",
}
