// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: Zhaoh0407.proto

/*
Package sample_package_0407 is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package sample_package_0407

import (
	"context"
	"io"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/v2/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Suppress "imported and not used" errors
var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray
var _ = metadata.Join

func request_Zhaoh0407Aaa_SayHello123_0(ctx context.Context, marshaler runtime.Marshaler, client Zhaoh0407AaaClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq HelloRequest
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.SayHello123(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_Zhaoh0407Aaa_SayHello123_0(ctx context.Context, marshaler runtime.Marshaler, server Zhaoh0407AaaServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq HelloRequest
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.SayHello123(ctx, &protoReq)
	return msg, metadata, err

}

// RegisterZhaoh0407AaaHandlerServer registers the http handlers for service Zhaoh0407Aaa to "mux".
// UnaryRPC     :call Zhaoh0407AaaServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterZhaoh0407AaaHandlerFromEndpoint instead.
func RegisterZhaoh0407AaaHandlerServer(ctx context.Context, mux *runtime.ServeMux, server Zhaoh0407AaaServer) error {

	mux.Handle("POST", pattern_Zhaoh0407Aaa_SayHello123_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateIncomingContext(ctx, mux, req, "/sample_module_0407.sample_package_0407.Zhaoh0407Aaa/SayHello123", runtime.WithHTTPPathPattern("/sample_module_0407.sample_package_0407.Zhaoh0407aaa/SayHello123"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_Zhaoh0407Aaa_SayHello123_0(rctx, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_Zhaoh0407Aaa_SayHello123_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

// RegisterZhaoh0407AaaHandlerFromEndpoint is same as RegisterZhaoh0407AaaHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterZhaoh0407AaaHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.Dial(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterZhaoh0407AaaHandler(ctx, mux, conn)
}

// RegisterZhaoh0407AaaHandler registers the http handlers for service Zhaoh0407Aaa to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterZhaoh0407AaaHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterZhaoh0407AaaHandlerClient(ctx, mux, NewZhaoh0407AaaClient(conn))
}

// RegisterZhaoh0407AaaHandlerClient registers the http handlers for service Zhaoh0407Aaa
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "Zhaoh0407AaaClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "Zhaoh0407AaaClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "Zhaoh0407AaaClient" to call the correct interceptors.
func RegisterZhaoh0407AaaHandlerClient(ctx context.Context, mux *runtime.ServeMux, client Zhaoh0407AaaClient) error {

	mux.Handle("POST", pattern_Zhaoh0407Aaa_SayHello123_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateContext(ctx, mux, req, "/sample_module_0407.sample_package_0407.Zhaoh0407Aaa/SayHello123", runtime.WithHTTPPathPattern("/sample_module_0407.sample_package_0407.Zhaoh0407aaa/SayHello123"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_Zhaoh0407Aaa_SayHello123_0(rctx, inboundMarshaler, client, req, pathParams)
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_Zhaoh0407Aaa_SayHello123_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

var (
	pattern_Zhaoh0407Aaa_SayHello123_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1}, []string{"sample_module_0407.sample_package_0407.Zhaoh0407aaa", "SayHello123"}, ""))
)

var (
	forward_Zhaoh0407Aaa_SayHello123_0 = runtime.ForwardResponseMessage
)
